version: '3'

services:

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SOCKET_SERVER=localhost:3001
    networks:
      - leaderboardsapp
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - MONGODB_CONNSTRING=mongodb://mongo_db:27017/scores_db
      #ATLAS - MONGODB_CONNSTRING=mongodb+srv://hhgsun:hhgsun@cluster0.yllgz.mongodb.net/scores_db?retryWrites=true&w=majority
    networks:
      - leaderboardsapp
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis_db
      - mongo_db

  mongo_db:
    image: mongo
    restart: on-failure
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: scores_db
    networks:
      - leaderboardsapp
    volumes:
      - mongodata:/data/db

  mongo-seed:
    build: ./db-seed
    networks:
      - leaderboardsapp
    links:
      - mongo_db

  redis_db:
    image: 'redis'
    restart: on-failure
    ports:
     - "6379:6379"
    networks:
      - leaderboardsapp
    volumes:
      - redisdata:/data/cache

networks:
  leaderboardsapp:
    driver: bridge

volumes:
  mongodata:
    driver: local
  redisdata:
    driver: local